//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadoApp.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleadoes
    {
        [Key]
        public int IdEmpleado { get; set; }
        public string strNombre { get; set; }
        public int IdRol { get; set; }
        public string strCargo { get; set; }
        public int IdProfesion { get; set; }
    }
}
