//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleadoApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCHEmpleado
    {
        public int IdEmpleado { get; set; }
        public string strNombre { get; set; }
        public string IdProfesion { get; set; }
        public string strProfesion { get; set; }
        public string strCargo { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string IdBarrio { get; set; }
        public string strBarrio { get; set; }
        public string IdUnidad { get; set; }
        public string strUnidad { get; set; }
        public string IdRegional { get; set; }
        public string strRegional { get; set; }
        public string IdProceso { get; set; }
        public string strProceso { get; set; }
        public string IdSubProceso { get; set; }
        public string strSubProceso { get; set; }
        public string IdJefe { get; set; }
        public string strNombreJefe { get; set; }
        public Nullable<System.DateTime> dtmFechaRetiro { get; set; }
        public Nullable<bool> LogClienteProveedor { get; set; }
        public Nullable<bool> LogGerenteRecursosH { get; set; }
        public int intSecuencia { get; set; }
        public Nullable<bool> LogEvaluar { get; set; }
        public string strUsuario { get; set; }
        public string strContrasena { get; set; }
        public Nullable<bool> logObjetivosLegalizados { get; set; }
        public Nullable<bool> logHabilitarIngresoObjPeriodoCerrado { get; set; }
        public Nullable<bool> logSuperUsuario { get; set; }
        public string strGrupoPago { get; set; }
        public string strUbicacion { get; set; }
        public Nullable<int> intNivel { get; set; }
        public string strSexo { get; set; }
        public string strRutaImagenEmpleado { get; set; }
        public Nullable<int> intPuntosAcumulados { get; set; }
        public Nullable<bool> logObjetivosAprobadosJefe { get; set; }
        public string strUsuarioRed { get; set; }
        public Nullable<bool> LogAplicaIntegracion { get; set; }
        public Nullable<bool> logAdmonVicepresidencia { get; set; }
        public string IdVicepresidenciaAdm { get; set; }
        public string Identificacion { get; set; }
        public string strCustom2 { get; set; }
        public Nullable<bool> logEsJefeEmp { get; set; }
        public Nullable<bool> logEvaluadoPeriodoPrueba { get; set; }
        public Nullable<bool> LogProrrogaPeriodoPrueba { get; set; }
        public Nullable<bool> logAdmonPeriodoPrueba { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<System.DateTime> dtmFechaIngreso { get; set; }
        public string strNombreGeneralista { get; set; }
        public string strUnidadFuncional { get; set; }
    }
}
